# Generated by Django 2.2.13 on 2020-08-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
